### ISSUE TITLE
Add TAP mode support.

### ISSUE THREAD

**Issue by tonyseek** [tonyseek/openvpn-status#1]
In TAP mode, `virtual_address` will be a virtual MAC address instead of a virtual IP address.

**Comment by nemesisdesign** [comment]
Stumbled upon this issue in @openwisp too.

**Comment by tonyseek** [comment]
The v0.2 release is coming soon. It will implement the TAP mode.

**Comment by rohithasrk** [comment]
Hi @tonyseek. Are you working on adding support to TAP mode? Would work on it if not.

**Comment by tonyseek** [comment]
I'm still working for it.

**Comment by nemesisdesign** [comment]
let us know if you need help

**Comment by tonyseek** [comment]
Hi @nemesisdesign @rohithasrk,

The openvpn-status 0.2.0 has been released to PyPI. The TAP mode (`virtual_addr` is a MAC instead of a IP) and client-config-dir (`virtual_addr` is a certain IP or a IP subnet) are compatible both now.

It is glad to hear that this library may help @openwisp.

Thanks for your encouragement.

**Comment by rohithasrk** [comment]
Thank you @tonyseek. :smile:

**Comment by nemesisdesign** [comment]
Thanks a lot @tonyseek, will send a link to a testing instance to show you what we are using it for :-)
