### ISSUE TITLE
ImportError: cannot import name python_2_unicode_compatible

### ISSUE THREAD

**Issue by txemi** [tonyseek/openvpn-status#3]
With python2

```
  File "/home/user/.local/lib/python2.7/site-packages/openvpn_status/utils.py", line 7, in <module>
    from six import python_2_unicode_compatible as unicode_compatible
ImportError: cannot import name python_2_unicode_compatible

```

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
```

**Comment by tonyseek** [comment]
Thank you for your feedback.

It is because the version of six is older than [1.9.0](https://bitbucket.org/gutworth/six/src/8b024292064c9d2fbd7a4f352c40b261b91fd058/CHANGES?fileviewer=file-view-default#CHANGES-27:33). I will constrain the six's version in setup.py and release a hotfix version soon.

**Comment by txemi** [comment]
I fixed it for me with "pip --user install --upgrade six"
As you said version I had in distro was old.
