### ISSUE TITLE
Let people choose if the bytes values must be humanized or not

### ISSUE THREAD

**Issue by lGuillaume124** [tonyseek/openvpn-status#9]
Hello,

First of all thank you for this useful Python module.

I'm trying to use it with a metrics collector system ([Telegraf](https://github.com/influxdata/telegraf)) to send detailed statistics to an InfluxDB database.
I didn't find in the documentation how to **not** *humanize* the values returned by ``Client.bytes_received`` and ``Client.bytes_sent``. Is it possible?

Guillaume.

**Comment by tonyseek** [comment]
Hi @lGuillaume124,

How about this?

```
print unicode(client.bytes_received)  # humanized text
print int(client.bytes_received)      # raw integer, the length of bytes
```

**Comment by lGuillaume124** [comment]
Indeed, thank you very much!
